// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfgncyerlcditfepasjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmZ25jeWVybGNkaXRmZXBhc2pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3NDQ2MTMsImV4cCI6MjA3ODMyMDYxM30.s6IptIujDq5TrJmEA5Oe8wXfKqMIGdArgtKLcQP3flE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});