// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frgeeutseqjzuddqdlls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyZ2VldXRzZXFqenVkZHFkbGxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0NDk2MTEsImV4cCI6MjA4NDAyNTYxMX0.UHtQx6KmEbxv8fR5rDfn_6UbVGTA-gxy5mRGhCzfnts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});